model_ver: 2

# [training setting]
train_split: train # (train/checking_train)
train_lr: 0.1
train_lr_adjust_rate: 0.001
train_lr_adjust_freq: 5
train_epoch_num: 50
train_save_freq: 5
train_print_freq: 10
train_batch_size: 64


# [testing setting]
test_split: val # (val/test/checking_val)
test_epoch: 20 # equal to train_epoch_num
test_batch_size: 64 # equal to train_batch_size


# [paths setting]
data_root: data
cache_root: cache
output_root: output
checkpoint_root: checkpoint











